name: Keep Alive Cron

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '*/20 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
    - name: Reset AvoDemo
      run: "curl -X GET -H 'Content-type: application/json' --data '{}' https://avodemo.herokuapp.com/avo"
